# Generated by Django 2.2.2 on 2019-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190619_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_number', models.IntegerField()),
                ('news_event', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
