# Generated by Django 2.2.2 on 2019-06-19 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20190619_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
