# Generated by Django 2.2.2 on 2019-06-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20190620_0014'),
        ('hello', '0004_new'),
    ]

    operations = [
    ]
